### ISSUE TITLE
applet intermittently fails to read data files in both 4.1.3 and 5.0

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/GIS-Extension#2]
sometimes it works, but there are intermittent failures, with all sorts of different error messages (sometimes a heap space error even if you're running with a ton of heap). it seems that when the extension reads data files their contents may intermittently be corrupted?

example of one of the errors you can get:

```text
java.io.IOException: unsupported shape type
at org.myworldgis.io.shapefile.ESRIShapeBuffer.getESRIRecord(ESRIShapeBuffer.java:132)
at org.myworldgis.io.shapefile.ESRIShapefileReader.getNextShape(ESRIShapefileReader.java:87)
at org.myworldgis.netlogo.LoadDataset.loadShapefile(LoadDataset.java:101)
at org.myworldgis.netlogo.LoadDataset.reportInternal(LoadDataset.java:189)
at org.myworldgis.netlogo.GISExtension$Reporter.report(GISExtension.java:40)
at org.nlogo.prim._externreport.report(_externreport.java:56)
at org.nlogo.prim._setobservervariable.perform(_setobservervariable.java:38)
at org.nlogo.nvm.Context.stepConcurrent(Context.java:99)
at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:90)
at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.java:181)
at org.nlogo.job.JobThread.run(JobThread.java:105)
```

Eric Russell writes:

>Upon closer investigation, it looks like it's actually some kind of 
>timing bug that results in a buffer underflow while reading from the 
>stream returned by URL.openStream. The stream reports that 8 bytes were 
>successfully read, but returns garbage values. Putting a 
>Thread.sleep(1000) between reading the header and reading the shape 
>records makes the problem go away, but it's not really a reliable 
>workaround. I'll have to look at the JDK source to see if I can figure 
>out what the root cause is [...]

**Comment by SethTisue** [comment]
we're no longer supporting applets
