### ISSUE TITLE
spurious JAI exception during automated testing on Linux

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/GIS-Extension#4]
the following prints when running nightly.sh on monk2.ccl.northwestern.edu.

perhaps we could modify this code:
http://jsexton0.blogspot.com/2007/09/cure-for-common-jai-exception.html
so it checks the message in the exception and only ignores our error in particular

```text
...............Error: Could not find mediaLib accelerator wrapper classes. Continuing in pure Java mode.
Occurs in: com.sun.media.jai.mlib.MediaLibAccessor
java.lang.NoClassDefFoundError: com/sun/medialib/mlib/Image
	at com.sun.media.jai.mlib.MediaLibAccessor$1.run(MediaLibAccessor.java:248)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.media.jai.mlib.MediaLibAccessor.setUseMlib(MediaLibAccessor.java:245)
	at com.sun.media.jai.mlib.MediaLibAccessor.useMlib(MediaLibAccessor.java:177)
	at com.sun.media.jai.mlib.MediaLibAccessor.isMediaLibCompatible(MediaLibAccessor.java:357)
	at com.sun.media.jai.mlib.MediaLibAccessor.isMediaLibCompatible(MediaLibAccessor.java:315)
	at com.sun.media.jai.mlib.MlibConvolveRIF.create(MlibConvolveRIF.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at javax.media.jai.FactoryCache.invoke(FactoryCache.java:122)
	at javax.media.jai.OperationRegistry.invokeFactory(OperationRegistry.java:1674)
	at javax.media.jai.ThreadSafeOperationRegistry.invokeFactory(ThreadSafeOperationRegistry.java:473)
	at javax.media.jai.registry.RIFRegistry.create(RIFRegistry.java:332)
	at javax.media.jai.RenderedOp.createInstance(RenderedOp.java:819)
	at javax.media.jai.RenderedOp.createRendering(RenderedOp.java:867)
	at javax.media.jai.RenderedOp.getWidth(RenderedOp.java:2179)
	at org.myworldgis.netlogo.RasterDataset.convolve(RasterDataset.java:602)
	at org.myworldgis.netlogo.RasterDatasetMath$Convolve.reportInternal(RasterDatasetMath.java:194)
	at org.myworldgis.netlogo.GISExtension$Reporter.report(GISExtension.java:40)
	at org.nlogo.prim._externreport.report(_externreport.java:56)
	at org.nlogo.prim._asm_setup_setprocedurevariable_4.perform()
	at org.nlogo.nvm.Context.stepConcurrent(Context.java:95)
	at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:99)
	at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.java:194)
	at org.nlogo.job.JobThread.run(JobThread.java:117)
Caused by: java.lang.ClassNotFoundException: com.sun.medialib.mlib.Image
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:627)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	... 27 more
```

**Comment by SethTisue** [comment]
not seeing this on Travis these days, e.g. https://travis-ci.org/NetLogo/NetLogo/builds/85836829, so probably no longer an issue

**Comment by nicolaspayette** [comment]
For future reference, it looks like this was fixed by `System.setProperty("com.sun.media.jai.disableMediaLib", "true")`: https://github.com/NetLogo/NetLogo/blob/464c6e9533c805215f4909e0094de6724ba78984/src/test/org/nlogo/headless/TestChecksums.scala#L22.
