### ISSUE TITLE
`import-wms-drawing` fails in GIS General Examples model with Internal Server Error (HTTP code 500)

### ISSUE THREAD

**Issue by EwoutH** [NetLogo/GIS-Extension#43]
In the [GIS General Examples](https://ccl.northwestern.edu/netlogo/models/GISGeneralExamples) model the `download-background-image` fails when calling `gis:import-wms-drawing` with the following error message:

```
Extension exception: Unable to fetch wms image:
http result code 500 (Internal Server Error) (URL: https://ows.terrestris.de/osm/service?Format=image/jpeg&Transparent=TRUE&Version=1.1.1&SRS=EPSG:4326&BBOX=-180,-90,62069,180,90,62069&Request=GetMap&Service=wms&Height=292&Layers=OSM-WMS&Width=580&Styles=)
error while observer running GIS:IMPORT-WMS-DRAWING
  called by procedure DOWNLOAD-BACKGROUND-IMAGE
  called by Button 'download-background-image'
```

In this example this code is executed:

```NetLogo
to download-background-image
  if-else projection = "WGS_84_Geographic" [
    gis:import-wms-drawing "https://ows.terrestris.de/osm/service?" "EPSG:4326" "OSM-WMS" 0
  ] [
    show "Only WGS_84_Geographic projections are supported. Please Change to WGS_84_Geographic in the top left drop-down."
  ]
end
```
And here is the full error message with internal details:
<details><summary>Full error message</summary>

```
Extension exception: Unable to fetch wms image:
http result code 500 (Internal Server Error) (URL: https://ows.terrestris.de/osm/service?Format=image/jpeg&Transparent=TRUE&Version=1.1.1&SRS=EPSG:4326&BBOX=-180,-90,62069,180,90,62069&Request=GetMap&Service=wms&Height=292&Layers=OSM-WMS&Width=580&Styles=)
error while observer running GIS:IMPORT-WMS-DRAWING
  called by procedure DOWNLOAD-BACKGROUND-IMAGE
  called by Button 'download-background-image'

org.nlogo.nvm.WrappedExtensionException: Extension exception: Unable to fetch wms image:
http result code 500 (Internal Server Error) (URL: https://ows.terrestris.de/osm/service?Format=image/jpeg&Transparent=TRUE&Version=1.1.1&SRS=EPSG:4326&BBOX=-180,-90,62069,180,90,62069&Request=GetMap&Service=wms&Height=292&Layers=OSM-WMS&Width=580&Styles=)
 at org.nlogo.prim._extern.perform(_extern.java:40)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
 at scala.util.control.Exception$Catch.apply(Exception.scala:228)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)
Caused by: org.nlogo.api.ExtensionException: Unable to fetch wms image:
http result code 500 (Internal Server Error) (URL: https://ows.terrestris.de/osm/service?Format=image/jpeg&Transparent=TRUE&Version=1.1.1&SRS=EPSG:4326&BBOX=-180,-90,62069,180,90,62069&Request=GetMap&Service=wms&Height=292&Layers=OSM-WMS&Width=580&Styles=)
 at org.myworldgis.netlogo.LoadWMSImage.performInternal(LoadWMSImage.java:76)
 at org.myworldgis.netlogo.GISExtension$Command.perform(GISExtension.java:61)
 at org.nlogo.prim._extern.perform(_extern.java:36)
 ... 8 more

NetLogo 6.3.0
main: org.nlogo.app.AppFrame
thread: JobThread
OpenJDK 64-Bit Server VM 17.0.3 (BellSoft; 17.0.3+7-LTS)
operating system: Windows 11 10.0 (amd64 processor)
Scala version 2.12.16
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: GIS General Examples

02:38:59.465 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
02:38:59.461 RuntimeErrorEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:38:59.461 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
02:38:59.461 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
02:38:59.461 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
02:38:59.461 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
02:38:59.461 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:38:59.380 AddJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
02:38:59.304 InputBoxLoseFocusEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
02:38:59.248 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
```
</details>

It could have to do with an API change in the [ows.terrestris.de](https://ows.terrestris.de/) service, but I'm not sure.

**Comment by all-the-way-down-turtles** [comment]
I have the same problem. It seems to me that the empty parameter ´Styles´ is the issue here. It works on my Linux computer, but not on Windows. 
It also worked with Netlogo 6.2.2, but since upgrading to Netlogo 6.3 it doesn't work any more.
